name: "✨ Feature Request"
description: "Suggest an idea for this project"
title: "Feat:"
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing request?
      description: Please search open and closed issues to see if this request has already been made.
      options:
        - label: I have searched for this request
          required: true
  - type: textarea
    attributes:
      label: Describe the feature request
      description: Please provide a concise description of the request, potential solutions, and additional context.
        required: true
  - type: checkboxes
    attributes:
      label: "Record"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I want to work on this issue"
